### ISSUE TITLE
kernel for seagull?

### ISSUE THREAD

**Issue by doraeric** [sonyxperiadev/vendor-sony-kernel#3]
Is there the seagull kernel?
I am building ROM for my xperia t3 d5103.
When I typed `make` , I got the error message:
`make: *** No rule to make target 'device/sony/common-kernel/kernel-dtb-seagull', needed by 'out/target/product/seagull/kernel'.  Stop.`

And apparently, the file does not exist.
Can I get the file from here?
Or maybe I just have to build it by myself?

**Comment by jerpelea** [comment]
please follow the build guide
seagull is not suported on M

**Comment by doraeric** [comment]
I didn't know seagull doesn't support Marshmallow...
Thanks for your explanation

**Comment by bartcubbins** [comment]
@jerpelea the question is settled. can be closed
